config/routes.rb
PaperclipS3Demo::Application.routes.draw do
  resources :pirates
  root to: "pirates#index"

end

app/models/pirate.rb
class Pirate < ActiveRecord::Base
  attr_accessible :beard_photo
  
  has_attached_file :beard_photo, :styles => {
    :big => "600x600>",
    :small => "100x100>"
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pirates_controller.rb
class PiratesController < ApplicationController
  # GET /pirates
  # GET /pirates.json
  def index
    @pirates = Pirate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pirates }
    end
  end

  # GET /pirates/1
  # GET /pirates/1.json
  def show
    @pirate = Pirate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pirate }
    end
  end

  # GET /pirates/new
  # GET /pirates/new.json
  def new
    @pirate = Pirate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pirate }
    end
  end

  # GET /pirates/1/edit
  def edit
    @pirate = Pirate.find(params[:id])
  end

  # POST /pirates
  # POST /pirates.json
  def create
    @pirate = Pirate.new(params[:pirate])

    respond_to do |format|
      if @pirate.save
        format.html { redirect_to @pirate, notice: 'Pirate was successfully created.' }
        format.json { render json: @pirate, status: :created, location: @pirate }
      else
        format.html { render action: "new" }
        format.json { render json: @pirate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pirates/1
  # PUT /pirates/1.json
  def update
    @pirate = Pirate.find(params[:id])

    respond_to do |format|
      if @pirate.update_attributes(params[:pirate])
        format.html { redirect_to @pirate, notice: 'Pirate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pirate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pirates/1
  # DELETE /pirates/1.json
  def destroy
    @pirate = Pirate.find(params[:id])
    @pirate.destroy

    respond_to do |format|
      format.html { redirect_to pirates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pirates_helper.rb
module PiratesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaperclipS3Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pirates/_form.html.erb
<%= form_for(@pirate) do |f| %>
  <% if @pirate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pirate.errors.count, "error") %> prohibited this pirate from being saved:</h2>

      <ul>
      <% @pirate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= f.label :beard_photo, "Upload your beard photo" %><br>
    <%= f.file_field :beard_photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pirates/edit.html.erb
<h1>Editing pirate</h1>

<%= render 'form' %>

<%= link_to 'Show', @pirate %> |
<%= link_to 'Back', pirates_path %>

app/views/pirates/index.html.erb
<h1>Listing pirates</h1>

<table>
  <tr>
    <th>Pirate ID</th>
    <th>Beard Photo</th>
    <th colspan="3">Actions</th>
  </tr>

<% @pirates.each do |pirate| %>
  <tr>
    <td><%= pirate.id %></td>
    <td><%= image_tag pirate.beard_photo.url(:small) %></td>
    <td><%= link_to 'Show', pirate %></td>
    <td><%= link_to 'Edit', edit_pirate_path(pirate) %></td>
    <td><%= link_to 'Destroy', pirate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pirate', new_pirate_path %>

app/views/pirates/new.html.erb
<h1>New pirate</h1>

<%= render 'form' %>

<%= link_to 'Back', pirates_path %>

app/views/pirates/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <%= image_tag @pirate.beard_photo.url(:big) %>
</div>

<%= link_to 'Edit', edit_pirate_path(@pirate) %> |
<%= link_to 'Back', pirates_path %>